# Generated by Django 4.2.3 on 2023-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
    ]
