# Generated by Django 4.2.3 on 2023-07-19 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=700)),
                ("ar_title", models.CharField(max_length=700)),
                ("pup_date", models.DateField(auto_now_add=True)),
                ("img", models.ImageField(upload_to="gallery/images/")),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to="galley/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
